title: Yassine BOUABDALLAOUI
logo: /data/img/my_photo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Social links for the sidebar
description: |
  <strong>ML Engineer, PhD, and Football Lover</strong>
  <br><br>
  ğŸŒ Located in France
  <br><br>
  ğŸ“„ <a href="/data/pdfs/my_cv.pdf" target="_blank">My CV</a>
  <br>
  ğŸŒ <a href="https://www.linkedin.com/in/yassine-bouabdallaoui/" target="_blank">LinkedIn Profile</a>
  <br>
  ğŸ“š <a href="https://www.researchgate.net/profile/Yassine-Bouabdallaoui" target="_blank">ResearchGate Profile</a>
  <br>
  âœï¸ <a href="https://medium.com/@bouabdallaoui.yassine" target="_blank">Medium Blog</a>
  