title: Yassine BOUABDALLAOUI
logo: /data/img/my_photo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Social links for the sidebar
description: | 
  **ML Engineer, PhD, and Football Lover**  
  <br>
  ğŸŒ [LinkedIn Profile](https://www.linkedin.com/in/yassine-bouabdallaoui/)  
  ğŸ“„ [ResearchGate Profile](https://www.researchgate.net/profile/Yassine-Bouabdallaoui)  
  âœï¸ [Medium Blog](https://medium.com/@bouabdallaoui.yassine)